# Generated by Django 4.1.7 on 2023-11-29 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import myapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.IntegerField(default=myapp.models.IntDefault, primary_key=True, serialize=False)),
                ('foto_account', models.ImageField(default='assets/image.svg', upload_to=myapp.models.user_directory_path)),
                ('type_account', models.CharField(choices=[('S', 'Superadmin'), ('P', 'PUBLIC'), ('V', 'VERIFIKATOR'), ('C', 'CHANNEL')], default='P', max_length=1)),
                ('deskripsi_account', models.TextField(blank=True, max_length=40000, null=True)),
                ('no_telpon', models.CharField(blank=True, max_length=20, null=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('verification_token', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
