# Generated by Django 4.1.7 on 2023-11-29 09:59

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.IntegerField(default=myapp.models.IntDefault, primary_key=True, serialize=False)),
                ('nama_channel', models.TextField(max_length=500, unique=True)),
                ('akronim', models.TextField(max_length=100)),
                ('deskripsi', models.TextField(blank=True, max_length=40000, null=True)),
                ('logo', models.ImageField(default='assets/default-logo-channel.svg', upload_to=myapp.models.user_directory_path)),
                ('isActive', models.BooleanField(default=False)),
                ('isModerated', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('daerah', models.CharField(blank=True, max_length=500, null=True)),
                ('alamat', models.CharField(blank=True, max_length=500, null=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='myapp.account')),
                ('pengelola', models.ManyToManyField(blank=True, related_name='pengelola', to='myapp.account')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.IntegerField(default=myapp.models.IntDefault, primary_key=True, serialize=False)),
                ('kategori_galeri', models.CharField(choices=[('UMKM', 'UMKM'), ('Pertanian', 'Pertanian'), ('Kesenian', 'Kesenian'), ('Pariwisata', 'Pariwisata'), ('Daerah', 'Daerah')], default='Daerah', max_length=20)),
                ('foto', models.ImageField(upload_to=myapp.models.user_directory_path)),
                ('deskripsi', models.TextField(blank=True, max_length=40000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='myapp.channel')),
            ],
        ),
        migrations.CreateModel(
            name='ContentVideo',
            fields=[
                ('id', models.IntegerField(default=myapp.models.IntDefault, primary_key=True, serialize=False)),
                ('judul_video', models.TextField(max_length=1000)),
                ('kategori_video', models.CharField(choices=[('UMKM', 'UMKM'), ('Pertanian', 'Pertanian'), ('Kesenian', 'Kesenian'), ('Pariwisata', 'Pariwisata'), ('Daerah', 'Daerah')], default='Daerah', max_length=20)),
                ('file_video', models.FileField(upload_to=myapp.models.user_directory_path)),
                ('thumbnail', models.ImageField(default='assets/thumbnail.svg', upload_to=myapp.models.user_directory_path)),
                ('deskripsi', models.TextField(blank=True, max_length=40000, null=True)),
                ('isMine', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='myapp.channel')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelVerification',
            fields=[
                ('id', models.IntegerField(default=myapp.models.IntDefault, primary_key=True, serialize=False)),
                ('foto_ktp', models.FileField(upload_to=myapp.models.user_directory_path)),
                ('surat_keterangan', models.FileField(upload_to=myapp.models.user_directory_path)),
                ('status_verifikasi', models.CharField(choices=[('pending', 'Menunggu Diverifikasi'), ('verified', 'Berhasil Diverifikasi'), ('rejected', 'Gagal Diverifikasi')], default='pending', max_length=20)),
                ('pesan', models.TextField(blank=True, max_length=40000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel', to='myapp.channel')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.IntegerField(default=myapp.models.IntDefault, primary_key=True, serialize=False)),
                ('kategori_artikel', models.CharField(choices=[('UMKM', 'UMKM'), ('Pertanian', 'Pertanian'), ('Kesenian', 'Kesenian'), ('Pariwisata', 'Pariwisata'), ('Daerah', 'Daerah')], default='Daerah', max_length=20)),
                ('judul_artikel', models.TextField(max_length=1000)),
                ('cover_artikel', models.ImageField(upload_to=myapp.models.user_directory_path)),
                ('konten_artikel', ckeditor.fields.RichTextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='myapp.channel')),
            ],
        ),
    ]
