# Generated by Django 4.1.7 on 2023-11-30 03:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_channel_gallery_contentvideo_channelverification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='end_pengelola',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='channel',
            name='start_pengelola',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
