# Generated by Django 4.1.7 on 2023-11-30 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_channel_end_pengelola_channel_start_pengelola'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='end_pengelola',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
