# Generated by Django 4.1.7 on 2023-11-30 08:05

from django.db import migrations, models
import django.db.models.deletion
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_channel_end_pengelola_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managerchannel',
            name='account_manager',
        ),
        migrations.RemoveField(
            model_name='managerchannel',
            name='created',
        ),
        migrations.RemoveField(
            model_name='managerchannel',
            name='end_managing',
        ),
        migrations.RemoveField(
            model_name='managerchannel',
            name='start_managing',
        ),
        migrations.RemoveField(
            model_name='managerchannel',
            name='updated',
        ),
        migrations.AlterField(
            model_name='managerchannel',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_channel', to='myapp.channel'),
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.IntegerField(default=myapp.models.IntDefault, primary_key=True, serialize=False)),
                ('start_managing', models.DateTimeField(blank=True, null=True)),
                ('end_managing', models.DateTimeField(blank=True, null=True)),
                ('account_manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='myapp.account')),
            ],
        ),
        migrations.AddField(
            model_name='managerchannel',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channel_managed', to='myapp.manager'),
        ),
    ]
