# Generated by Django 4.1.7 on 2023-11-30 08:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_managerchannel_account_manager_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managerchannel',
            name='manager',
        ),
        migrations.AddField(
            model_name='managerchannel',
            name='account_manager',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='myapp.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='managerchannel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='managerchannel',
            name='end_managing',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managerchannel',
            name='start_managing',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managerchannel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='managerchannel',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_managed', to='myapp.channel'),
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
