# Generated by Django 4.1.7 on 2023-11-30 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_managerchannel_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='myapp.account'),
        ),
    ]
