# Generated by Django 4.1.7 on 2023-12-06 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_article_created_alter_article_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type_account',
            field=models.CharField(choices=[('S', 'Superadmin'), ('P', 'PUBLIC'), ('V', 'VERIFIKATOR'), ('C', 'CHANNEL'), ('CM', 'CHANNEL MANAGER')], default='P', max_length=10),
        ),
    ]
