# Generated by Django 4.1.7 on 2023-12-06 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_account_type_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentvideo',
            old_name='isMine',
            new_name='isAccepted',
        ),
        migrations.AddField(
            model_name='contentvideo',
            name='creator',
            field=models.ForeignKey(default='owner', on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='myapp.account'),
            preserve_default=False,
        ),
    ]
