# Generated by Django 4.1.7 on 2023-12-06 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_rename_ismine_contentvideo_isaccepted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentvideo',
            name='creator',
        ),
    ]
