# Generated by Django 4.1.7 on 2023-12-06 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_contentvideo_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentvideo',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='myapp.account'),
            preserve_default=False,
        ),
    ]
