# Generated by Django 4.1.7 on 2023-12-06 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_contentvideo_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentvideo',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_video', to='myapp.account'),
        ),
    ]
