# Generated by Django 4.1.7 on 2023-12-06 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_contentvideo_updated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentvideo',
            name='updated_by',
        ),
    ]
