# Generated by Django 4.1.7 on 2023-12-07 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_remove_contentvideo_isaccepted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='isAccepted',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='isAccepted',
        ),
    ]
