# Generated by Django 4.1.7 on 2023-12-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_remove_article_isaccepted_remove_gallery_isaccepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pesan_status',
            field=models.TextField(blank=True, max_length=40000, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('pending', 'Menunggu Direview'), ('accepted', 'Diterima'), ('rejected', 'Ditolak')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='gallery',
            name='pesan_status',
            field=models.TextField(blank=True, max_length=40000, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='status',
            field=models.CharField(choices=[('pending', 'Menunggu Direview'), ('accepted', 'Diterima'), ('rejected', 'Ditolak')], default='pending', max_length=20),
        ),
    ]
