# Generated by Django 4.1.7 on 2023-12-12 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_article_pesan_status_article_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type_account',
            field=models.CharField(choices=[('S', 'SUPERADMIN'), ('P', 'PUBLIC'), ('V', 'VERIFIKATOR'), ('C', 'CHANNEL'), ('CM', 'CHANNEL MANAGER'), ('R', 'REVIEWER')], default='P', max_length=10),
        ),
    ]
