# Generated by Django 4.1.7 on 2023-12-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_alter_account_type_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type_account',
            field=models.CharField(choices=[('A', 'ADMIN'), ('P', 'PUBLIC'), ('V', 'VERIFIKATOR'), ('C', 'CHANNEL'), ('CM', 'CHANNEL MANAGER'), ('R', 'REVIEWER')], default='P', max_length=10),
        ),
    ]
