# Generated by Django 4.1.7 on 2023-12-13 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='article',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='article',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='account',
        ),
        migrations.RemoveField(
            model_name='channelverification',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='contentvideo',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='contentvideo',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='contentvideo',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='managerchannel',
            name='account_manager',
        ),
        migrations.RemoveField(
            model_name='managerchannel',
            name='channel',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Channel',
        ),
        migrations.DeleteModel(
            name='ChannelVerification',
        ),
        migrations.DeleteModel(
            name='ContentVideo',
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.DeleteModel(
            name='ManagerChannel',
        ),
    ]
