# Generated by Django 4.1.7 on 2023-12-13 14:00

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import myapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0031_remove_article_channel_remove_article_creator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.IntegerField(default=myapp.models.IntDefault, primary_key=True, serialize=False)),
                ('foto_account', models.ImageField(default='assets/image.svg', upload_to=myapp.models.user_directory_path)),
                ('type_account', models.CharField(choices=[('A', 'ADMIN'), ('P', 'PUBLIC'), ('V', 'VERIFIKATOR'), ('C', 'CHANNEL'), ('CM', 'CHANNEL MANAGER'), ('R', 'REVIEWER')], default='P', max_length=10)),
                ('deskripsi_account', models.TextField(blank=True, max_length=40000, null=True)),
                ('no_telpon', models.CharField(blank=True, max_length=20, null=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('verification_token', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.IntegerField(default=myapp.models.IntDefault, primary_key=True, serialize=False)),
                ('nama_channel', models.TextField(max_length=500, unique=True)),
                ('akronim', models.TextField(max_length=100)),
                ('deskripsi', models.TextField(blank=True, max_length=40000, null=True)),
                ('logo', models.ImageField(default='assets/default-logo-channel.svg', upload_to=myapp.models.user_directory_path)),
                ('isActive', models.BooleanField(default=False)),
                ('isModerated', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('daerah', models.CharField(blank=True, max_length=500, null=True)),
                ('alamat', models.CharField(blank=True, max_length=500, null=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='myapp.account')),
            ],
        ),
        migrations.CreateModel(
            name='ManagerChannel',
            fields=[
                ('id', models.IntegerField(default=myapp.models.IntDefault, primary_key=True, serialize=False)),
                ('start_managing', models.DateTimeField(blank=True, null=True)),
                ('end_managing', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('account_manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='myapp.account')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_managed', to='myapp.channel')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.IntegerField(default=myapp.models.IntDefault, primary_key=True, serialize=False)),
                ('kategori_galeri', models.CharField(choices=[('UMKM', 'UMKM'), ('Pertanian', 'Pertanian'), ('Kesenian', 'Kesenian'), ('Pariwisata', 'Pariwisata'), ('Daerah', 'Daerah')], default='Daerah', max_length=20)),
                ('foto', models.ImageField(upload_to=myapp.models.user_directory_path)),
                ('deskripsi', models.TextField(blank=True, max_length=40000, null=True)),
                ('status', models.CharField(choices=[('pending', 'Menunggu Direview'), ('accepted', 'Diterima'), ('rejected', 'Ditolak')], default='pending', max_length=20)),
                ('pesan_status', models.TextField(blank=True, max_length=40000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_galery', to='myapp.channel')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_gallery', to='myapp.account')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_gallery', to='myapp.account')),
            ],
        ),
        migrations.CreateModel(
            name='ContentVideo',
            fields=[
                ('id', models.IntegerField(default=myapp.models.IntDefault, primary_key=True, serialize=False)),
                ('judul_video', models.TextField(max_length=1000)),
                ('kategori_video', models.CharField(choices=[('UMKM', 'UMKM'), ('Pertanian', 'Pertanian'), ('Kesenian', 'Kesenian'), ('Pariwisata', 'Pariwisata'), ('Daerah', 'Daerah')], default='Daerah', max_length=20)),
                ('file_video', models.FileField(upload_to=myapp.models.user_directory_path)),
                ('thumbnail', models.ImageField(default='assets/thumbnail.svg', upload_to=myapp.models.user_directory_path)),
                ('deskripsi', models.TextField(blank=True, max_length=40000, null=True)),
                ('status', models.CharField(choices=[('pending', 'Menunggu Direview'), ('accepted', 'Diterima'), ('rejected', 'Ditolak')], default='pending', max_length=20)),
                ('pesan_status', models.TextField(blank=True, max_length=40000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_videos', to='myapp.channel')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='myapp.account')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_video', to='myapp.account')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelVerification',
            fields=[
                ('id', models.IntegerField(default=myapp.models.IntDefault, primary_key=True, serialize=False)),
                ('foto_ktp', models.FileField(upload_to=myapp.models.user_directory_path)),
                ('surat_keterangan', models.FileField(upload_to=myapp.models.user_directory_path)),
                ('status_verifikasi', models.CharField(choices=[('pending', 'Menunggu Diverifikasi'), ('verified', 'Berhasil Diverifikasi'), ('rejected', 'Gagal Diverifikasi')], default='pending', max_length=20)),
                ('pesan', models.TextField(blank=True, max_length=40000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_verification', to='myapp.channel')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.IntegerField(default=myapp.models.IntDefault, primary_key=True, serialize=False)),
                ('kategori_artikel', models.CharField(choices=[('UMKM', 'UMKM'), ('Pertanian', 'Pertanian'), ('Kesenian', 'Kesenian'), ('Pariwisata', 'Pariwisata'), ('Daerah', 'Daerah')], default='Daerah', max_length=20)),
                ('judul_artikel', models.TextField(max_length=1000)),
                ('cover_artikel', models.ImageField(upload_to=myapp.models.user_directory_path)),
                ('konten_artikel', ckeditor.fields.RichTextField()),
                ('status', models.CharField(choices=[('pending', 'Menunggu Direview'), ('accepted', 'Diterima'), ('rejected', 'Ditolak')], default='pending', max_length=20)),
                ('pesan_status', models.TextField(blank=True, max_length=40000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_article', to='myapp.channel')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_article', to='myapp.account')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_article', to='myapp.account')),
            ],
        ),
    ]
