# Generated by Django 4.1.7 on 2023-12-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type_account',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('PUBLIC', 'PUBLIC'), ('VERIFIKATOR', 'VERIFIKATOR'), ('CHANNEL', 'CHANNEL'), ('CHANNEL MANAGER', 'CHANNEL MANAGER'), ('REVIEWER', 'REVIEWER')], default='PUBLIC', max_length=20),
        ),
    ]
