# Generated by Django 4.1.7 on 2023-12-23 14:50

from django.db import migrations, models
import django.db.models.deletion
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_rename_likes_contentvideo_liked_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeGallery',
            fields=[
                ('id', models.IntegerField(default=myapp.models.IntDefault, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.account')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.gallery')),
            ],
        ),
        migrations.AddField(
            model_name='gallery',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_galleries', through='myapp.LikeGallery', to='myapp.account'),
        ),
    ]
