# Generated by Django 4.1.7 on 2023-12-23 15:52

from django.db import migrations, models
import django.db.models.deletion
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_likegallery_gallery_liked_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeArticle',
            fields=[
                ('id', models.IntegerField(default=myapp.models.IntDefault, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.account')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.article')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_article', through='myapp.LikeArticle', to='myapp.account'),
        ),
    ]
